name: Docker build and push
on: 
  push:
    paths:
      - 'main.py'
      - 'Dockerfile'
      - 'requirements.txt'
      - '.github/workflows/docker_build_push.yml'
jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASS }}
  #buildx:
    #runs-on: ubuntu-latest
    #steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
  #build_push:
    #runs-on: ubuntu-latest
    #steps:
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: arseniiyamnii/rkn-checker
